# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import BookStore_pb2 as BookStore__pb2


class BookStoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LocalStorePS = channel.unary_unary(
                '/BookStore/LocalStorePS',
                request_serializer=BookStore__pb2.LocalStorePSRequest.SerializeToString,
                response_deserializer=BookStore__pb2.LocalStorePSResponse.FromString,
                )
        self.CreateChain = channel.unary_unary(
                '/BookStore/CreateChain',
                request_serializer=BookStore__pb2.CreateChainRequest.SerializeToString,
                response_deserializer=BookStore__pb2.CreateChainResponse.FromString,
                )
        self.ListChain = channel.unary_unary(
                '/BookStore/ListChain',
                request_serializer=BookStore__pb2.ListChainRequest.SerializeToString,
                response_deserializer=BookStore__pb2.ListChainResponse.FromString,
                )
        self.WriteOperation = channel.unary_unary(
                '/BookStore/WriteOperation',
                request_serializer=BookStore__pb2.WriteOperationRequest.SerializeToString,
                response_deserializer=BookStore__pb2.WriteOperationResponse.FromString,
                )
        self.ListBooks = channel.unary_unary(
                '/BookStore/ListBooks',
                request_serializer=BookStore__pb2.ListBooksRequest.SerializeToString,
                response_deserializer=BookStore__pb2.ListBooksResponse.FromString,
                )
        self.ReadOperation = channel.unary_unary(
                '/BookStore/ReadOperation',
                request_serializer=BookStore__pb2.ReadOperationRequest.SerializeToString,
                response_deserializer=BookStore__pb2.ReadOperationResponse.FromString,
                )
        self.Timeout = channel.unary_unary(
                '/BookStore/Timeout',
                request_serializer=BookStore__pb2.TimeoutRequest.SerializeToString,
                response_deserializer=BookStore__pb2.TimeoutResponse.FromString,
                )
        self.DataStatus = channel.unary_unary(
                '/BookStore/DataStatus',
                request_serializer=BookStore__pb2.DataStatusRequest.SerializeToString,
                response_deserializer=BookStore__pb2.DataStatusResponse.FromString,
                )
        self.RemoveHead = channel.unary_unary(
                '/BookStore/RemoveHead',
                request_serializer=BookStore__pb2.RemoveHeadRequest.SerializeToString,
                response_deserializer=BookStore__pb2.RemoveHeadResponse.FromString,
                )
        self.RestoreHead = channel.unary_unary(
                '/BookStore/RestoreHead',
                request_serializer=BookStore__pb2.RestoreHeadRequest.SerializeToString,
                response_deserializer=BookStore__pb2.RestoreHeadResponse.FromString,
                )


class BookStoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LocalStorePS(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateChain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListChain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Timeout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DataStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveHead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestoreHead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LocalStorePS': grpc.unary_unary_rpc_method_handler(
                    servicer.LocalStorePS,
                    request_deserializer=BookStore__pb2.LocalStorePSRequest.FromString,
                    response_serializer=BookStore__pb2.LocalStorePSResponse.SerializeToString,
            ),
            'CreateChain': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateChain,
                    request_deserializer=BookStore__pb2.CreateChainRequest.FromString,
                    response_serializer=BookStore__pb2.CreateChainResponse.SerializeToString,
            ),
            'ListChain': grpc.unary_unary_rpc_method_handler(
                    servicer.ListChain,
                    request_deserializer=BookStore__pb2.ListChainRequest.FromString,
                    response_serializer=BookStore__pb2.ListChainResponse.SerializeToString,
            ),
            'WriteOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteOperation,
                    request_deserializer=BookStore__pb2.WriteOperationRequest.FromString,
                    response_serializer=BookStore__pb2.WriteOperationResponse.SerializeToString,
            ),
            'ListBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBooks,
                    request_deserializer=BookStore__pb2.ListBooksRequest.FromString,
                    response_serializer=BookStore__pb2.ListBooksResponse.SerializeToString,
            ),
            'ReadOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadOperation,
                    request_deserializer=BookStore__pb2.ReadOperationRequest.FromString,
                    response_serializer=BookStore__pb2.ReadOperationResponse.SerializeToString,
            ),
            'Timeout': grpc.unary_unary_rpc_method_handler(
                    servicer.Timeout,
                    request_deserializer=BookStore__pb2.TimeoutRequest.FromString,
                    response_serializer=BookStore__pb2.TimeoutResponse.SerializeToString,
            ),
            'DataStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.DataStatus,
                    request_deserializer=BookStore__pb2.DataStatusRequest.FromString,
                    response_serializer=BookStore__pb2.DataStatusResponse.SerializeToString,
            ),
            'RemoveHead': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveHead,
                    request_deserializer=BookStore__pb2.RemoveHeadRequest.FromString,
                    response_serializer=BookStore__pb2.RemoveHeadResponse.SerializeToString,
            ),
            'RestoreHead': grpc.unary_unary_rpc_method_handler(
                    servicer.RestoreHead,
                    request_deserializer=BookStore__pb2.RestoreHeadRequest.FromString,
                    response_serializer=BookStore__pb2.RestoreHeadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'BookStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BookStore(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LocalStorePS(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BookStore/LocalStorePS',
            BookStore__pb2.LocalStorePSRequest.SerializeToString,
            BookStore__pb2.LocalStorePSResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateChain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BookStore/CreateChain',
            BookStore__pb2.CreateChainRequest.SerializeToString,
            BookStore__pb2.CreateChainResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListChain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BookStore/ListChain',
            BookStore__pb2.ListChainRequest.SerializeToString,
            BookStore__pb2.ListChainResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WriteOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BookStore/WriteOperation',
            BookStore__pb2.WriteOperationRequest.SerializeToString,
            BookStore__pb2.WriteOperationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BookStore/ListBooks',
            BookStore__pb2.ListBooksRequest.SerializeToString,
            BookStore__pb2.ListBooksResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BookStore/ReadOperation',
            BookStore__pb2.ReadOperationRequest.SerializeToString,
            BookStore__pb2.ReadOperationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Timeout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BookStore/Timeout',
            BookStore__pb2.TimeoutRequest.SerializeToString,
            BookStore__pb2.TimeoutResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DataStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BookStore/DataStatus',
            BookStore__pb2.DataStatusRequest.SerializeToString,
            BookStore__pb2.DataStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveHead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BookStore/RemoveHead',
            BookStore__pb2.RemoveHeadRequest.SerializeToString,
            BookStore__pb2.RemoveHeadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RestoreHead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BookStore/RestoreHead',
            BookStore__pb2.RestoreHeadRequest.SerializeToString,
            BookStore__pb2.RestoreHeadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
