def bookshop_welcome():
    print("------------------WELCOME TO THE ONLINE BOOK SHOP!-----------------------------")
    print("Here's how to use the system:")
    print("1. Each node(computer) will act as a server and a client using the same port and id.")
    print("2. Start by 'Local-store-ps' to create data store processes on your local node.")
    print("3. Run the 'Create-chain' to create a replication chain for strong data consistency once the data store processes are created.")
    print("4. Use the 'Write-operation' command to add or update the price of a book.")
    print("5. Use the 'List-books' command to view the available books in the store.")
    print("6. Use the 'Read-operation' command to retrieve the price of a particular book.")
    print("7. Use the 'List-chain' command to list the current status of the replication chain.")
    print("8. Use the 'Time-out' command to set the timeout for propagating write updates between processes.")
    print("9. Use the 'Data-status' command to list the status of each data item, whether clean or dirty.")
    print("10. Use the 'Remove-head' command to remove the current head from the chain.")
    print("11. Use the 'Restore-head' command to restore the most recent removed head back to the chain.")
    print("Note: Each command should be run on the node where you want to perform the operation.")
    print("Thank you for using our online book shop system!")
